## Renders elves as billboard chibi sprites.
##
## Creates one Sprite3D per elf with BILLBOARD_ENABLED. Each elf gets a
## unique chibi texture generated by SpriteFactory using the elf's index
## as a seed for deterministic variety. Positions are updated each frame
## from SimBridge.
##
## See also: sprite_factory.gd for texture generation, sim_bridge.rs for
## elf position data, main.gd which creates this node and calls setup().

extends Node3D

var _bridge: SimBridge
var _elf_sprites: Array[Sprite3D] = []


## Call after SimBridge is initialized.
func setup(bridge: SimBridge) -> void:
	_bridge = bridge


func _process(_delta: float) -> void:
	if _bridge == null or not _bridge.is_initialized():
		return

	var positions := _bridge.get_elf_positions()
	var elf_count := positions.size()

	# Add sprites if we have more elves than sprites.
	while _elf_sprites.size() < elf_count:
		var idx := _elf_sprites.size()
		var params = SpriteFactory.elf_params_from_seed(idx)
		var sprite := Sprite3D.new()
		sprite.texture = SpriteFactory.create_chibi_elf(params)
		sprite.billboard = BaseMaterial3D.BILLBOARD_ENABLED
		sprite.pixel_size = 0.06  # Scale: 48px * 0.06 = 2.88 world units
		sprite.transparent = true
		sprite.no_depth_test = false
		add_child(sprite)
		_elf_sprites.append(sprite)

	# Hide excess sprites.
	for i in _elf_sprites.size():
		if i < elf_count:
			_elf_sprites[i].visible = true
			var pos := positions[i]
			# Offset Y by ~1.5 so the sprite stands on top of the voxel.
			_elf_sprites[i].global_position = Vector3(pos.x + 0.5, pos.y + 1.5, pos.z + 0.5)
		else:
			_elf_sprites[i].visible = false
